title: Nimrod (Nim) Dvir
first_name: Nimrod
middle_name: (Nim)
last_name: Dvir
email: ndvir@albany.edu
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Personal website of Nim Dvir. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Nim Dvir is a UX and AI researcher
keywords: UX, AI, HCI, Jekyll, academic-website, portfolio-website
lang: en
icon: ⚛️
url: https://nimdvir.github.io/
baseurl: ""
last_updated: false
impressum_path: ""
back_to_top: true

# Third-party libraries
third_party_libraries:
  download: false
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
    version: "1.22.4"
  # Add other libraries as needed

# Other configurations...

