# Site settings
title: Nim Dvir - Personal Website
email: ndvir@albany.edu
description: > 
  Personal website of Nim Dvir, featuring my portfolio, blog, and publications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nimdvir.github.io" # the base hostname & protocol for your site
github_username: nimdvir
linkedin_username: nimdvir

# Social links
social:
  linkedin: https://www.linkedin.com/in/nimdvir
  google_scholar: https://bit.ly/ndvirgscholar
  twitter: 
  github: https://github.com/nimdvir
  email: ndvir@albany.edu

# Analytics
google_analytics: G-0PZ8NW81X4
google_site_verification: VQxw8QuMHnjgy6nsv_vRvzDutyNsjwolTAGZHhZ4doU

# Blog settings
blog_name: Blog
blog_description: Insights on UX, AI, and HCI.
permalink: /blog/:year/:title/
lsi: true

# Pagination
pagination:
  enabled: true

# Related blog posts
related_blog_posts:
  enabled: true
  max_related: 5

# Giscus comments (if you want to enable comments)
giscus:
  repo: nimdvir/your-repo-name
  repo_id: your-repo-id
  category: Comments
  category_id: your-category-id
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme

# Get external JSON data
jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
