version: '3.9'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --host=0.0.0.0 --port=8080
    ports:
      - '8080:8080'
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
